### PR TITLE
Updating vendor requirements and fixes broken tests

### PR DESCRIPTION
**Pull request by bigfoot90**
Updating vendor requirements and fixes broken tests
Solves https://github.com/ElectricMaxxx/DoctrineOrmOdmAdapter/issues/38
Replaces https://github.com/ElectricMaxxx/DoctrineOrmOdmAdapter/pull/39

### CODE REVIEW

**Comment by ElectricMaxxx** [comment]
The conflicts are based on the reverted #39 ?

**Comment by bigfoot90** [comment]
@ElectricMaxxx yes

**Comment by bigfoot90** [comment]
I can rebase

**Comment by ElectricMaxxx** [comment]
yes, please.

**Comment by bigfoot90** [comment]
Done, tests are ok.

**Comment by ElectricMaxxx** [comment]
Uhh yea, thanks a lot.

**Pull request merged**
