### PR TITLE
Allow install with newer doctrine's versions

### PR DESCRIPTION
**Pull request by bigfoot90**
Solves https://github.com/ElectricMaxxx/DoctrineOrmOdmAdapter/issues/38

### CODE REVIEW

**Comment by ElectricMaxxx** [comment]
Thanks for the quick fix.

**Comment by ElectricMaxxx** [comment]
Uhh didn't watch the tests on mobile. :-(

**Comment by bigfoot90** [comment]
Sorry for that. 

I've reverted to your last commit before this, but I'm unable to run rour tests. I'm missing something?
```
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Doctrine\Common\Annotations\AnnotationReader::__construct() must be an instance of Doctrine\Common\Annotations\DocParser, instance of Doctrine\Common\Cache\ArrayCache given, called in /home/bigfoot/projects/bigfoot/DoctrineOrmOdmAdapter/tests/Doctrine/Tests/ORM/ODMAdapter/Functions/BaseFunctionalTestCase.php on line 191 and defined in /home/bigfoot/projects/bigfoot/DoctrineOrmOdmAdapter/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationReader.php:157
Stack trace:
#0 /home/bigfoot/projects/bigfoot/DoctrineOrmOdmAdapter/tests/Doctrine/Tests/ORM/ODMAdapter/Functions/BaseFunctionalTestCase.php(191): Doctrine\Common\Annotations\AnnotationReader->__construct(Object(Doctrine\Common\Cache\ArrayCache))
#1 /home/bigfoot/projects/bigfoot/DoctrineOrmOdmAdapter/tests/Doctrine/Tests/ORM/ODMAdapter/Functions/BaseFunctionalTestCase.php(65): Doctrine\Tests\ORM\ODMAdapter\Functions\BaseFunctionalTestCase->createObjectAdapterManager()
#2 /home/bigfoot/projects/bigfoot in /home/bigfoot/projects/bigfoot/DoctrineOrmOdmAdapter/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationReader.php on line 157
```

**Comment by bigfoot90** [comment]
**edit:** I'm using ```php 7.0```

**Comment by ElectricMaxxx** [comment]
I have no idea. I am on holliday until until sunday. So i have got no other device than my phone. I think we have to wait until then.

**Comment by bigfoot90** [comment]
OK, no problem.
I've solved installing vendors with ```composer update --prefer-stable```.

**Pull request merged**
